<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="root" nsPrefix="root">
  <eSubpackages name="p1">
    <eClassifiers xsi:type="ecore:EClass" name="c1a"/>
    <eClassifiers xsi:type="ecore:EClass" name="c1b"/>
    <eClassifiers xsi:type="ecore:EClass" name="c1c"/>
    <eSubpackages name="p11">
      <eClassifiers xsi:type="ecore:EClass" name="c11a"/>
      <eClassifiers xsi:type="ecore:EClass" name="c11b"/>
      <eSubpackages name="p111">
        <eClassifiers xsi:type="ecore:EClass" name="c111a"/>
        <eClassifiers xsi:type="ecore:EClass" name="c111b"/>
        <eClassifiers xsi:type="ecore:EClass" name="c111c"/>
        <eClassifiers xsi:type="ecore:EClass" name="c111d"/>
        <eClassifiers xsi:type="ecore:EClass" name="c111e"/>
        <eClassifiers xsi:type="ecore:EClass" name="c111f"/>
        <eClassifiers xsi:type="ecore:EClass" name="c111g"/>
        <eClassifiers xsi:type="ecore:EClass" name="c111h"/>
        <eSubpackages name="p1111">
          <eClassifiers xsi:type="ecore:EClass" name="c1111"/>
        </eSubpackages>
        <eSubpackages name="p1112">
          <eClassifiers xsi:type="ecore:EClass" name="c1112a"/>
          <eClassifiers xsi:type="ecore:EClass" name="c1112b"/>
        </eSubpackages>
        <eSubpackages name="p1113">
          <eClassifiers xsi:type="ecore:EClass" name="c1113"/>
        </eSubpackages>
      </eSubpackages>
      <eSubpackages name="p112">
        <eClassifiers xsi:type="ecore:EClass" name="c112"/>
        <eSubpackages name="p1121"/>
        <eSubpackages name="p1122">
          <eClassifiers xsi:type="ecore:EClass" name="c1122a"/>
          <eClassifiers xsi:type="ecore:EClass" name="c1122b"/>
          <eClassifiers xsi:type="ecore:EClass" name="c1122c"/>
          <eClassifiers xsi:type="ecore:EClass" name="c1122d"/>
          <eClassifiers xsi:type="ecore:EClass" name="c1122e"/>
          <eClassifiers xsi:type="ecore:EClass" name="c1122f"/>
          <eClassifiers xsi:type="ecore:EClass" name="c1122g"/>
          <eClassifiers xsi:type="ecore:EClass" name="c1122h"/>
          <eClassifiers xsi:type="ecore:EClass" name="c1122i"/>
          <eClassifiers xsi:type="ecore:EClass" name="c1122j"/>
        </eSubpackages>
        <eSubpackages name="p1123"/>
      </eSubpackages>
    </eSubpackages>
    <eSubpackages name="p12">
      <eClassifiers xsi:type="ecore:EClass" name="c12a"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12b"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12c"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12d"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12e"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12f"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12g"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12h"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12i"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12j"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12k"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12l"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12m"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12n"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12o"/>
      <eClassifiers xsi:type="ecore:EClass" name="c12p"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
